### PR TITLE
Issue #14: Added json serialization support for ChessGame class.

### PR DESCRIPTION
**Pull request by nvrnight**
I don't have Visual Studio so was unable to run the unit tests to verify that they still work. I did play through some games and tested all the scenarios I could think of though and everything seemed to be working fine still. If you see any problems just let me know and I'll fix it right up.

### CODE REVIEW

**Comment by ProgramFOX** [comment]
I realize I forgot to comment to your original issue (sorry about that!), so: `ChessGame.GetFen` was actually supposed to be used for serialization. `ChessGame` also has a constructor taking a FEN, and the process of GetFen and then the constructor is 100% lossless (de)serialization. Is there any reason to prefer JSON serialization over that (which has the cost of having to provide public setters on all properties)?

**Comment by nvrnight** [comment]
Ah, yeah I never would've run across that without someone telling me about it. It's not documented anywhere. I'll go ahead and switch over to using that most likely. Thanks for the info.

The reason to prefer JSON is because it's a fairly standard format of serializing/deserializing that most everyone is familiar with. Both can be done with one liners(JSON.NET) that wouldn't require any custom logic for you to maintain in your GetFen or LoadFen functionality.
JsonConvert.SerializeObject(gameObject, new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.All });
JsonConvert.DeserializeObject<ChessGame>(jsonString, new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.All });

**Comment by ProgramFOX** [comment]
Hm, there are actually 3 properties not covered by the FEN serialization: DrawClaimed, DrawReason and Resigned. I'll check if there is a way to indicate that serialization must happen through a combination of the FEN and those three properties, in such a way that you can still do such a one-liner.

**Comment by nvrnight** [comment]
I was more implying the benefits apply to you more than the consumers. The benefit of the consumer is that they don't have to know about the custom way of serializing/deserializing. The benefit for you is that you don't have to maintain custom serialization/deserialization logic.

Now that I know about using the FEN functionality I can just use it instead of serializing to json so I'm perfectly fine using that, I was just pointing out the benefits of Json since you asked, it really won't have an effect on me either way anymore now that I have a maintained way of doing the serializing. I'm just saving and restoring game state when I shutdown my service running so that the games can be restored when it starts back up.

**Comment by nvrnight** [comment]
Actually that's a good catch polytomous, Board probably doesn't need to be made public since it's a calculated value. The only properties that need to be made public are those that were already public a public get and those needed to keep the game'ss "state". But I'm guessing at this point this pull request can get thrown away entirely due to having a way of serializing/deserializing already.

**Comment by ProgramFOX** [comment]
Yes - I'm not really a fan of properties having a public `set` if they shouldn't actually be accessed from the outside.

@nvrnight again sorry for not having responded earlier and having wasted your time!

**Pull request closed without merging**
